#spring:
#  ai:
#    mcp:
#      server:
#        name: vicep-mcp-server
#        version: 0.0.1
#        base-url: "/viacep/v0"
#        instructions: "Esse server prove informações de endereços."

# Using spring-ai-starter-mcp-server-webmvc
spring:
  ai:
    mcp:
      server:
        name: vicep-mcp-server
        version: 0.0.1
        type: SYNC
        instructions: "Esse server prove informações de endereços."

logging:
  level:
    io:
      modelcontextprotocol: ${LOG_LEVEL:DEBUG}

